language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

cache: pip

services:
    - redis-server
    - mongodb

install:
    - pip install -q -U pip
    - pip install -q -r requirements.txt
    - pushd cvesearch/scripts/db
    - ./manage.py -p
    # Avoid creating a log > 4mb and making travis unhappy.
    - ./manage_cpe.py | cat &
    - PID=$!
    - while sleep 60; do kill -0 $PID && echo 'Still running' || break; done
    - popd
    #- pushd web
    #- python minimal-web.py &
    #- popd

script:
    - pushd cvesearch/scripts
    - ./search.py -p cisco:ios:12.4 > /dev/null
    - ./search.py -p cisco:ios:12.4 -o json > /dev/null
    - ./search.py -p microsoft:windows_7 -o html > /dev/null
    - ./search.py -c CVE-2010-3333 > /dev/null
    - ./dump_last.py -f atom -l 2 > /dev/null
    - popd

notifications:
    email:
        on_success: change
        on_failure: change
